name: Static Web Apps

on:
  push:
    branches:
      - master

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: actions/setup-node@v6
        with:
          node-version: "latest"

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: "latest"
          cache: true
          run_install: false

      - name: Build
        run: pnpm install && pnpm build

      - name: Pages Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          cname: Aloen.to
